### ISSUE TITLE
Visual Studio Code 扩展 | 前端物语

### ISSUE THREAD

**Issue by maomao1996** [maomao1996/mm-notes#31]
/mm-notes/software/vscode.html

**Comment by ZHANGLUInfinite** [comment]
vscode的配置是不是和.eslintrc.js匹配着来最好?

**Comment by maomao1996** [comment]
> @ZHANGLUInfinite
> vscode的配置是不是和.eslintrc.js匹配着来最好?
> 

是的，新版本的最好配置一样，不然会有规则冲突

**Comment by YxrSadhu** [comment]
茂神，你这紫色让我后悔尝试了下（狗头

**Comment by maomao1996** [comment]
> @YxrSadhu
> 茂神，你这紫色让我后悔尝试了下（狗头

是不是爱上了

**Comment by YxrSadhu** [comment]
> > @YxrSadhu
> > 茂神，你这紫色让我后悔尝试了下（狗头
> 
> 是不是爱上了

我枯了🙈

**Comment by maomao1996** [comment]
> @YxrSadhu
> > > @YxrSadhu
> > > 茂神，你这紫色让我后悔尝试了下（狗头
> > 
> > 是不是爱上了
> 
> 我枯了🙈

不，你爱了😏

**Comment by h7ml** [comment]
"files.associations": {
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript",
    "*.vue": "vue"
  },

建议``files.associations``添加配置，格式化vue文件

**Comment by maomao1996** [comment]
> @h7ml
> ``` javascript
>   "files.associations": {
>     "*.cjson": "jsonc",
>     "*.wxss": "css",
>     "*.wxs": "javascript",
>     "*.vue": "vue"
>   },
> ```
> 
> 建议``files.associations``添加配置，格式化vue文件

好的，感谢反馈
