### ISSUE TITLE
请问关灯特效怎么实现的啊？请教，感谢！

### ISSUE THREAD

**Issue by shelley-xl** [maomao1996/mm-notes#86]

**Comment by maomao1996** [comment]
你说的关灯特效指的是主题切换特效吗

**Comment by shelley-xl** [comment]
是的，右上角白天黑夜切换特效




清风徐来
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maomao1996/mm-notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月28日(星期六) 晚上9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [maomao1996/mm-notes] 请问关灯特效怎么实现的啊？请教，感谢！ (Issue #86)





 
你说的关灯特效指的是主题切换特效吗

**Comment by maomao1996** [comment]
https://vitepress.dev/guide/extending-default-theme#on-appearance-toggle 这里有文档说明的
