### ISSUE TITLE
config文件base配置

### ISSUE THREAD

**Issue by SiMuZhang** [maomao1996/mm-notes#92]
config文件设置 `base: process.env.APP_BASE_PATH || '/',`，打包部署出来界面样式是错乱的， 百度说把`base`设置成`base: './',`，这样本地打包是正常的，但是部署出来第一时间会有画面但是一会又变成404了。拉取了你的代码，打包出来的dist文件也是错乱的，
![image](https://github.com/maomao1996/mm-notes/assets/102848714/37bd4794-b3f9-4ed9-b3d1-ebc824c39d6f)

我看你的博客是正常的，请问大佬这个应该怎么去解决啊

**Comment by maomao1996** [comment]
你的 base 没有配置正确，嫌麻烦可以直接使用这个模板 https://github.com/maomao1996/vitepress-nav-template

**Comment by SiMuZhang** [comment]
但是我看我那个base跟你的是一样的呀，没搞懂

**Comment by maomao1996** [comment]
github 部署和其他的部署是不一样的

**Comment by SiMuZhang** [comment]
那page部署是使用 GitHub Actions 还是使用 Deploy from a branch

**Comment by maomao1996** [comment]
都是用的 GitHub Actions 自动部署

**Comment by SiMuZhang** [comment]
好的，我试试你的模版，谢谢了
